### ISSUE TITLE
Conflict with Parse SDK

### ISSUE THREAD

**Issue by tomlongo** [Adonit/JotTouchSDK#31]
I'm getting linker errors when using on a project with the Parse SDK, i believe it has something to do with the linker flags -ObjC -all_load. Is there a way around this so that I can use both in the same project?

**Comment by jarbogast** [comment]
Hi Tom,

One thing you can try is to remove the -all_load flag (but keep the -ObjC flag). You shouldn't really need that flag for the JotTouch SDK since -all_load only applies to the rare case where you are trying to link a library that contains ONLY categories and no classes.

Honestly though, I'm betting your issues will still persist. Can you let me know what symbols are conflicting. That'll give us a better indication of what the solution to your problem might look like.

**Comment by tomlongo** [comment]
Hey mate, thanks for the help. You're right, the problems still occur after removing the all_load flag. I've attached a screenshot of the error log to help. 
![jot](https://cloud.githubusercontent.com/assets/1435382/7612794/11c13dca-f9cc-11e4-89c0-a1c0039834e8.gif)

**Comment by jarbogast** [comment]
No worries. From that error log, it looks like Parse simply doesn't contain those symbols for the architecture you're building for (the simulator). I'm only mildly familiar with Parse, but maybe they don't provide binaries to use on the simulator? What happens when you try to build and run on an actual device?

I also don't see anything to do with the Jot Touch SDK other than the fact that you are indeed linking it with your application. What makes you think that the our SDK is causing the problem?

**Comment by jarbogast** [comment]
Ah and actually when I look closer, those missing symbols are from the Accounts and Social frameworks from Apple. And those frameworks aren't in the linked frameworks that I can see in your screenshot. Make sure you're linking in those two frameworks since apparently Parse needs them!

**Comment by tomlongo** [comment]
you're right they're from Parse but only occurred when the -ObjC flag is added. 

Thanks for your help though it set me on a path to find a workaround to the issue via this SO answer http://stackoverflow.com/questions/15457136/parse-for-ios-errors-when-trying-to-run-the-app
